repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v4.4.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.42.0
          - eslint-plugin-angular@4.1.0
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
