version: '3.4'

services:
  super-linter:
    image: github/super-linter:v3.15.5
    environment:
    - RUN_LOCAL=true
    - VALIDATE_MARKDOWN=false
    - VALIDATE_NATURAL_LANGUAGE=false
    - VALIDATE_JAVASCRIPT_STANDARD=false
    - IGNORE_GITIGNORED_FILES=true
    volumes:
    - .:/tmp/lint/
  angularngrxshoppingcart:
    image: angularngrxshoppingcart
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
